management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://mypostgresservername2023.postgres.database.azure.com:1433/blog-complete?sslmode=require
    username: myusernamepost
    password: mypasswordpostMSA!
    name: blog-complete

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

info:
  application:
    name: blog-complete
    description: A blog with articles about The Spring Framework.
    author: Marlon Amedee
    version: '@project.version@'