##spring.datasource.url=jdbc:sqlserver://mysqlserver-blogger-2023.database.windows.net:1433;database=mydatabase-blogger-2023;user=azureuser-MSA@mysqlserver-blogger-2023;password={1e47y565eijd)!h|=mAYx,Wq'~c?{s};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
##spring.datasource.username=azureuser-MSA
##spring.datasource.password=1e47y565eijd)!h|=mAYx,Wq'~c?{s
##
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
##spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
##spring.jpa.hibernate.ddl-auto=update
###spring.sql.init.data-locations=classpath:/db/schema.sql
#
##spring.datasource.url=jdbc:mysql://localhost:3306/MARLON_BLOG_DB
##spring.datasource.username=root
##spring.datasource.password=hello-r-fmT(I9sp8pu9[Q$l}KNyDiYD,U#x
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.hibernate.ddl-auto=create
#
##spring.datasource.url=jdbc:sqlserver://mysqlserver-blogger-2023.database.windows.net
##server.port=1433
#
##spring.datasource.url=jdbc:sqlserver://mysqlserver-blogger-2023.database.windows.net:1433;database=mydatabase-blogger-2023;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
##spring.datasource.url=jdbc:sqlserver://mysqlserver-blogger-2023.database.windows.net:1433;database=mydatabase-blogger-2023;user=azureuser-MSA@mysqlserver-blogger-2023;password={1e47y565eijd)!h|=mAYx,Wq'~c?{s};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
##spring.datasource.username=azureuser-MSA
##spring.datasource.password=1e47y565eijd)!h|=mAYx,Wq'~c?{s
##spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
##spring.jpa.hibernate.ddl-auto=create
#
#spring.datasource.url=jdbc:mysql://mysqlserver-blogger-2023.mysql.database.azure.com/mydatabase-blogger-2023?useSSL=true&requireSSL=false&serverTimezone=UTC
#spring.datasource.username=azureuser-MSA@mysqlserver-blogger-2023
#spring.datasource.password=1e47y565eijd)!h|=mAYx,Wq'~c?{s
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
