spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLPlusDialect

# Database Connection URL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# A connection timeout fallback for direct connections
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update