spring.datasource.driver-class-name=org.postgresql.Driver

# Let Spring Boot 3 automatically use its native Hibernate 6 PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database Connection URL with SSL enabled (Required for Supabase direct connections)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Keep connection attempts alive during cold starts
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update