MY_HOST=mysqldbserver2023.database.windows.net
MY_DATABASE=mysqldb
MY_USERNAME=myadmin
MY_PASSWORD=mypassword@2023
ADMIN_SERVER=myadmin@mysqldbserver2023
APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=8e53c9e5-6033-4d89-84fd-fc9052dbb704;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/
