-- CREATE TABLE IF NOT EXISTS `authority` (
--     `name` varchar(16) NOT NULL,
--     PRIMARY KEY (`name`)
--     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- CREATE TABLE IF NOT EXISTS `post` (
--     `id` bigint NOT NULL AUTO_INCREMENT,
--     `title` varchar(255) NOT NULL,
--     `content` text NOT NULL,
--     `created_on` varchar(255) NOT NULL,
--     `updated_on` varchar(255) NOT NULL,
--     `user_id` bigint NOT NULL,
--     PRIMARY KEY (`id`),
--     UNIQUE KEY `uk_post_title` (`title`),
--     CONSTRAINT `fk_post_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
--     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- CREATE TABLE IF NOT EXISTS `post_tags` (
--    `post_id` bigint NOT NULL,
--    `tag` varchar(255) NOT NULL,
--     KEY `fk_post_tags_post_id` (`post_id`),
--     CONSTRAINT `fk_post_tags_post_id` FOREIGN KEY (`post_id`) REFERENCES `post` (`id`) ON DELETE CASCADE
--     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- CREATE TABLE IF NOT EXISTS `user` (
--     `id` bigint NOT NULL AUTO_INCREMENT,
--     `username` varchar(255) DEFAULT NULL,
--     `email` varchar(255) DEFAULT NULL,
--     `password` varchar(255) DEFAULT NULL,
--     `role` varchar(255) DEFAULT NULL,
--     PRIMARY KEY (`id`),
--     UNIQUE KEY `uk_user_username` (`username`),
--     UNIQUE KEY `uk_user_email` (`email`)
--     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- CREATE TABLE IF NOT EXISTS `user_authority` (
--     `user_id` bigint NOT NULL,
--     `authority_name` varchar(16) NOT NULL,
--     KEY `fk_user_authority_user_id` (`user_id`),
--     KEY `fk_user_authority_authority_name` (`authority_name`),
--     CONSTRAINT `fk_user_authority_authority_name` FOREIGN KEY (`authority_name`) REFERENCES `authority` (`name`) ON DELETE CASCADE,
--     CONSTRAINT `fk_user_authority_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
--     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
-- INSERT INTO Authority (name) VALUES ('ROLE_GUEST'), ('ROLE_ADMIN');
--
-- INSERT INTO user (username, email, password, role)
-- VALUES ('Marlon', 'mamedee001@gmail.com', '$2a$10$yOLSbb009NBBUo/eOw0jkOtY2J3qhj0gWENRlXXRttbKXQ0sGYWkq', 'ROLE_ADMIN');
--
-- INSERT INTO user_authority (user_id, authority_name)
-- VALUES (1, 'ROLE_ADMIN');